# Generated by Django 2.1 on 2018-08-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('email',)},
        ),
    ]
