# Generated by Django 2.1 on 2018-08-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autentication', '0002_auto_20180827_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_exercicio', models.IntegerField(verbose_name='Dias de exercicio por semana')),
                ('glicemia_em_jejum', models.FloatField(verbose_name='Glicemia em jejum (mg/mL)')),
                ('glicemia_pos_refeicao', models.FloatField(verbose_name='Glicemia pos refeicao (mg/mL)')),
                ('fuzzy_result', models.FloatField(verbose_name='Resultado Fuzzy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autentication.Usuario')),
            ],
        ),
    ]
